name: BuildImage-Dev

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  DevImage:
    runs-on: 
      - self-hosted
      - linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            prefix={{branch}}-
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/davehamer/website-ichbs
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value={{sha}}
            type=raw,value={{date 'YYYY-MM-DDTHHmmss.SSS'}}
            type=raw,value=latest
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile
          context: ./src
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
